### ISSUE TITLE
请问项目上线了吗？

### ISSUE THREAD

**Issue by wsgzxl** [LiuFeng1011/MajiangServer#1]
请问项目上线过吗？

**Comment by LiuFeng1011** [comment]
上线过，只上了2个月，不赚钱就关了，是h5的客户端，当时时间比较紧，如果用的话有些地方还需要优化

发自我的 iPhone

在 2018年3月11日，23:54，wsgzxl <notifications@github.com<mailto:notifications@github.com>> 写道：


请问项目上线过吗？

**Comment by wsgzxl** [comment]
我看到是单线程处理的，单线程处理的过来吗？
